# Read the Docs configuration file
version: 2

# Define the build environment
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

# Sphinx configuration
sphinx:
  configuration: docs/conf.py

# Install dependencies
python:
  install:
    - requirements: docs/requirements.txt